# This is a basic workflow to help you get started with Actions

name: Bicep Template Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  validate: 
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Log in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'AzureUSGovernment'
        enable-AzPSSession: false

    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        deploymentName: ${{ github.run_number }}
        scope: subscription
        subscriptionId: ${{ secrets.ARM_SUBSCRIPTION }}
        template: ./main.bicep
        # parameters: environmentType=${{ env.ENVIRONMENT_TYPE }}
        region: usgovvirginia
        failOnStdErr: false
        deploymentMode: Validate